[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
etherlink_testnet = "https://node.ghostnet.etherlink.com"
etherlink_mainnet = "https://node.mainnet.etherlink.com"

# Chain information
[profile.chains]
etherlink_testnet = 128123
etherlink_mainnet = 42793

[etherscan]
etherlink_testnet = { key = "DUMMY", url = "https://testnet.explorer.etherlink.com/api" }
etherlink_mainnet = { key = "DUMMY", url = "https://explorer.etherlink.com/api" }
